### PR TITLE
Update systemd requirement

### PR DESCRIPTION
**Pull request by jfroche**

### CODE REVIEW

**Comment by TheMeier** [comment]
Thanks

could you please update this to drop the ref in fixtures and set the metadata to < 2.0.0

**Comment by jfroche** [comment]
No problem to do that change, I would like to understand your point of view first.
My point of view is that metadata describe the known compatible version of the module dependencies and fixtures is there to define precisely what version of the dependencies we tested the code with.

**Comment by TheMeier** [comment]
>  If your module is compatible with the latest released versions of its dependencies, set the upper bound to exclude the next, unreleased major version.

https://puppet.com/docs/puppet/5.4/modules_metadata.html#best-practice-set-an-upper-bound-for-version

Also I like to keep the  fixtures uncapped so test fail early. Actually it seems to be common practice to set  the fixtures version to the git HEAD

**Comment by TheMeier** [comment]
https://github.com/TheMeier/puppet-systemd_cron/commit/5081a47f7b9b29ae4560faa5d07f309c56484fd0

**Pull request closed without merging**
