### PR TITLE
add posibility to add monotonic timers

### PR DESCRIPTION
**Pull request by trefzer**

### CODE REVIEW

**Comment by TheMeier** [comment]
@trefzer thank you for your contribution. Could you add a basic test for the new parameters?

**Comment by TheMeier** [comment]
@trefzer I changed the parameter names to include `_sec` and be Integers.

**Comment by trefzer** [comment]
@TheMeier Better make it Integer OR String, it's possible to specify the time with '5min' to indicate 5 Minutes.
About spec tests, I can do that, but do not have the time currently.

**Comment by TheMeier** [comment]
@trefzer I see, I simply assumed parameters ending in `Sec` would only accept seconds. Checked the docs and you are right. I also added a basic test already.

**Pull request merged**
